# Import the relevant libraries

In [16]:
import numpy as np

# Declaring scalars, vectors, and matrices

## Scalars

In [17]:
s = 5

In [18]:
s

5

## Vectors

In [19]:
v = np.array([5,-2,4])

In [20]:
v

array([ 5, -2,  4])

## Matrices

In [21]:
m = np.array([[5,12,6],[-3,0,14]])

In [22]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data types

In [23]:
type(s)

int

In [24]:
type(v)

numpy.ndarray

In [25]:
type(m)

numpy.ndarray

In [26]:
s_array = np.array([5])

In [27]:
type(s_array)

numpy.ndarray

## Data shapes

In [28]:
m.shape

(2, 3)

In [29]:
v.shape

(3,)

In [30]:
s_array.shape

(1,)

## Creating a column vector

In [31]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [32]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [33]:
m+s

array([[10, 17, 11],
       [ 2,  5, 19]])

In [34]:
m+s_array

array([[10, 17, 11],
       [ 2,  5, 19]])

In [35]:
v+s

array([10,  3,  9])

In [36]:
v

array([ 5, -2,  4])

In [37]:
v+s_array

array([10,  3,  9])

In [38]:
m+v

array([[10, 10, 10],
       [ 2, -2, 18]])